//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_ventas_peliculas_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int IdCompras { get; set; }
        public int UsuarioId { get; set; }
        public int IdPeliculas { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public string EstadoPago { get; set; }
        public int CantidadComprada { get; set; }
    
        public virtual Peliculas Peliculas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
