//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_ventas_peliculas_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportesVentas
    {
        public long Id { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public decimal VentasTotales { get; set; }
        public string PeliculasMasVendidas { get; set; }
    }
}
